server:
  port: 8080
  servlet:
    context-path: /bootpre


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.201:3306/SellDB?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

limit:
  minMoney: 10.0
  maxMoney: 1000.0
  description: 最少要发${limit.minMoney}, 最多发${limit.maxMoney}


girl:
  name: Lily
  age: 18
  phone: 65585672

minMoney: 2.0
description: 最小金额${minMoney}元